### ISSUE TITLE
Not sure if this is an issue - but I blogged about Seth.

### ISSUE THREAD

**Issue by rudimk** [andrejewski/seth#1]
Absolutely loved Seth. I played with it, and I think it's an amazing DSL.
I also ended up blogging about it. Hope you like it! You could check it out [here](http://blog.mathharbor.com/seth-set-theory-with-javascript/).

**Comment by andrejewski** [comment]
Thank you very much, Rudraksh. Set theory is a really cool branch of mathematics that has gone un-implemented. (Even in Haskell, there is only [one library](https://hackage.haskell.org/package/type-settheory).) I am glad to see someone else appreciates Seth. 

This is not an issue, so I will close this. If you would like to discuss further, my email address is on my profile and I would be happy to correspond.
