### ISSUE TITLE
Testing cartesian product on multiple sets.

### ISSUE THREAD

**Issue by fsvieira** [andrejewski/seth#4]
Hi,

I think seth is an amazing idea, so I am doing some tests to try to understand the lib, my motivation is to investigate how well combinatorial explosion is handled by seth.

But right now I am just doing simple stuff.

So I have this code:

```
const Seth = require('seth');
const Set = Seth.Set;

const allDiff = Set(function(x) {
	let e = [];
	console.log(JSON.stringify(x));
	
	for (let i=0; i<x.length; i++) {
		if (e.includes(x[i])) {
			// console.log(JSON.stringify(e) + " => " + x[i]);
			return false;
		}
		
		e.push(x[i]);
	}
	
	return true;
});


const digits = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
const diff = allDiff.intersect(Set(digits).cartesianProduct(Set(digits)));

console.log(diff.hasMember([1, 1])); // return false [OK]
console.log(diff.hasMember([1, 2])); // return true [OK]

const comb = diff.cartesianProduct(Set(digits));
console.log(comb.hasMember([1, 1, 1])); // return true [NOT OK]
console.log(comb.hasMember([1, 2, 3])); // return true [OK]

```
The idea of allDiff function is have sets where elements are arrays/tuples where all elements are different, and then I intesect it with cartasian product of two digits sets making tuples of (0, 0), (0, 1) ... (9, 9). Then I test with hasMember and it seems to give good result, but then I tried to make cartesian product of this diff set with another digits set, and I think it should give me a set with elements like:
(x, y, z) where x != y and x, y, z in [0...9] .

I am probably doing some big confusion, but can you help me understand better the concepts to achieve my goal. 

Thanks.

**Comment by andrejewski** [comment]
The problem is the 3 value tuple. When you are doing nested cartesian products, Seth doesn't flatten the tuples. Querying like this gives the desired result:

```
comb.hasMember([1, [2, 3]]) // true
comb.hasMember([1, [1, 1]]) // false
```

Looking at https://github.com/andrejewski/seth/blob/master/lib/index.js#L79 we see that a tuple of `[1, 1]` is technically a member as 1 is a member of `Set(digits)`.

Due to the element value agnostic nature of Seth, I don't think the flattened tuple syntax is one that could be supported; certainly confusing without digging into the source.

---

Full updated example:
```
const Seth = require('seth');
const Set = Seth.Set;

const allDiff = Set(function(x) {
	let e = [];
	// console.log(JSON.stringify(x));
	
	for (let i=0; i<x.length; i++) {
		if (e.includes(x[i])) {
			// console.log(JSON.stringify(e) + " => " + x[i]);
			return false;
		}
		
		e.push(x[i]);
	}
	
	return true;
});

const digits = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
const diff = allDiff.intersect(Set(digits).cartesianProduct(Set(digits)));

console.log(diff.hasMember([1, 1])); // return false [OK]
console.log(diff.hasMember([1, 2])); // return true [OK]

const comb = diff.cartesianProduct(Set(digits));
console.log(comb.hasMember([1, [1, 1]])); // return false [OK]
console.log(comb.hasMember([1, [2, 3]])); // return true [OK]
```

**Comment by fsvieira** [comment]
Hi, thanks for the answer, the syntax is ok. I am really just trying to understand the lib. Thanks.
